### ISSUE TITLE
Bug:queue.py

### ISSUE THREAD

**Issue by chengcxy** [tenlee2012/scrapy-kafka-redis#1]
Base类
_encode_request 方法 需要返回序列化的数据
_decode_request 方法 需要反序列化数据
KafkaQueue类
push方法 
self.producer.send(self.topic, value=self._encode_request(request).encode('utf-8'))

**Comment by chengcxy** [comment]
不好意思 没注意看配置文件里已经加了value_serializer参数
KAFKA_REQUEST_PRODUCER_PARAMS = {
    'api_version': (0, 10, 1),
    'value_serializer': dumps
}
# Constructing a Kafka consumer of the request queue
KAFKA_REQUEST_CONSUMER_PARAMS = {
    'api_version': (0, 10, 1),
    'value_deserializer': loads
}
# Constructing a Kafka consumer in the start queue
KAFKA_START_URLS_CONSUMER_PARAMS = {
    'api_version': (0, 10, 1),
    'value_deserializer': lambda m: m.decode('utf-8'),
}

**Comment by tenlee2012** [comment]
开源以来一直很期待bug，失望了
